#bin/sh

function plogo() {
	logodisplay=$(sudo python /home/pi/RetroPie/BIOS/lcd/lcdlogos.py $1)
	eval $logodisplay
}





plogo "logottm"
plogo "micropolis"
plogo "smw"
plogo "openttd"
plogo "kodi"
plogo "gba"
plogo "wonderswancolor"
plogo "ngpc"
plogo "quake3"
plogo "wonderswan"
plogo "dreamcast"
plogo "gbc"
plogo "ngp"
plogo "n64"
plogo "quake"
plogo "psx"
plogo "sega32x"
plogo "doom"
plogo "duke3d"
plogo "segacd"
plogo "gamegear"
plogo "neogeo"
plogo "snes"
plogo "samcoupe"
plogo "xrick"
plogo "genesis"
plogo "megadrive"
plogo "pc"
plogo "pcengine"
plogo "scummvm"
plogo "atari7800"
plogo "amiga"
plogo "atarist"
plogo "mastersystem"
plogo "amstradcpc"
plogo "macintosh"
plogo "daphne"
plogo "msx"
plogo "nes"
plogo "oric"
plogo "sg-1000"
plogo "atari5200"
plogo "c64"
plogo "coleco"
plogo "vectrex"
plogo "zxspectrum"
plogo "dragon32"
plogo "gb"
plogo "ti99"
plogo "coco"
plogo "gameandwatch"
plogo "intellivision"
plogo "zmachine"
plogo "mame-mame4all"
plogo "videopac"
plogo "apple2"
plogo "atari800"
plogo "atari2600"
plogo "logottm"
